## CSE422 lab: Genetic Algorithm

#### Genetic Algorithm Pseudo code:



**function** GENETIC-ALGORITHM( population, FITNESS-FN) **returns** an individual 
 
> **inputs:** population- a set of individuals/chromosomes; FITNESS-FN- a function that measures the fitness of an individual

>**repeat** 
new_population $\leftarrow$ empty set 
>>**for** $i=1$ **to** size ($ population$) **do**
$$
\begin{array}{l}
x \leftarrow \text { RANDOM-SELECTION }(\text { population, FITNESS-FN }) \\
y \leftarrow \text { RANDOM-SELECTION }(\text { population, FITNESS-FN }) \\
child  \leftarrow \operatorname{CROSSOVER}(x, y)
\end{array}
$$
>>>**if** (some_random_number < mutation_threshold) **then** child$\leftarrow$ MUTATE ( child ) 

>>>add child to new_population 

>>population $\leftarrow$ new_population 

>**until** some individual is fit enough, or enough time has elapsed

>**return** the best individual in population, according to FITNESS-FN
 


### Skeleton Code:

### Importing libraries

In [111]:
import numpy as np
import math

### Fitness function

In [163]:
def fitness(population, n):

    '''calculates the fitness score of each
        of the individuals in the population
        
        returns a 1D numpy array: index referring to 
        ith individual in population, and value referring 
        to the fitness score.'''
    fitness_result = []
    fitness_summation = []
    for chromosome in population:
        summation = np.sum(chromosome)
        fitness_summation.append(summation)
    zero_pos=[]
    for a in range(len(fitness_summation)):
        if fitness_summation==0:
            zero_pos.append(a)
        else:
            x=1/np.absolute(fitness_summation[a])
            fitness_result.append(x)
    print(np.sum(chromosome))
    fitness_result=np.array(fitness_result)
    zero_value_probability=(1-np.sum(fitness_result))/len(zero_pos)
    for a in zero_pos:
        fitness_result[a]=zero_value_probability 
    
    multiplier = 1/np.sum(fitness_result)
    for x in range(len(fitness_result)):
        fitness_result[x] *= multiplier
    return fitness_result

### Random Selection function

This built-in function might help to create the weighted random selection:

`numpy.random.choice(a, size, replace, p)` 

`p` are the weights of the individuals- value between 0 and 1; refers to the probability of each individual being selected.

`a` is the array

`size` how many samples to return

`replace = True`

In [81]:
def select(population, fit):
    ''' take input:  population and fit
        fit contains fitness values of each of the individuals 
        in the population  
        
        return:  one individual randomly giving
        more weight to ones which have high fitness score'''
    #a = [0,1,2,3,4]
    a = [a for a in range(len(population))]
    #size = 1
    #p = [.31, .29, 0.26, 0.14]
    print(fit)
    print(population)
    selected = np.random.choice(a,len(population),True,fit)
    selected = [population[a] for a in selected]
    #print(selected)
    return selected


### Crossover function


**function** CROSSOVER $(x, y)$ **returns** an individual 

>**inputs**: $x, y$  which are the parent individuals

>$n \leftarrow \mathrm{LENGTH}(x) ; c \leftarrow$ random number from 1 to $n$ 

>**return** APPEND(SUBSTRING $(x, 1, c),$ SUBSTRING $(y, c+1, n))$

In [158]:
def crossover(x, y):
    '''take input: 2 parents - x, y. 
        Generate a random crossover point. 
        Append first half of x with second 
        half of y to create the child
        
        returns: a child chromosome'''
    crossover_point = np.random.randint(2,len(x)-2)
    temp_1=np.concatenate((x[0:crossover_point],y[crossover_point:]))
    #temp_2=np.concatenate((y[0:crossover_point],x[crossover_point:]))
    
    
    return temp_1

###Mutation function

In [ ]:
def mutate(child):
    '''take input: a child
        mutates a random 
        gene into another random gene
        
        returns: mutated child'''
    

    return 

### Genetic Algorithm Function

In [ ]:
def GA(population, n, mutation_threshold = 0.3):
    '''implement the pseudocode here by
        calling the necessary functions- Fitness, 
        Selection, Crossover and Mutation
        
        print: the max fitness value and the 
        chromosome that generated it which is ultimately 
        the solution board'''




    return

Running the Genetic Algorithm function

In [164]:
'''for 8 queen problem, n = 8'''
n = 8

'''start_population denotes how many individuals/chromosomes are there
  in the initial population n = 8'''
start_population = 10 

'''if you want you can set mutation_threshold to a higher value,
   to increase the chances of mutation'''
mutation_threshold = 0.3

'''creating the population with random integers between 0 to 7 inclusive
   for n = 8 queen problem'''
population = np.random.randint(0, 2, (start_population, n))

'''calling the GA function'''
#GA(population, n, mutation_threshold)
x=fitness(population,len(population))
y=select(population,x)
z=crossover(y[0],y[1])
print(z)

-3
[ 0.  0.  0.  0.  0. nan  0.  0.  0.  0.]
[[ 1 -7 -1 -2  7 -1 -1  2]
 [ 7  4  7  2  5 -3 -4 -8]
 [ 5 -4  0  6  4 -5  2 -3]
 [-7  3 -6 -7 -6  3  3  1]
 [-4  5  0  0  0 -1  0  7]
 [ 4 -6  7 -2  1  0 -4  0]
 [-3  7 -4 -8  7 -6  3  2]
 [ 6 -8 -2  3  4 -2 -4 -1]
 [ 2 -5  6 -8 -3 -5 -4  4]
 [ 3  7 -8  5 -4  2 -2 -6]]


C:\Users\User\AppData\Local\Temp/ipykernel_11560/565511450.py:20: RuntimeWarning: divide by zero encountered in long_scalars
  x=1/np.absolute(fitness_summation[a])
C:\Users\User\AppData\Local\Temp/ipykernel_11560/565511450.py:30: RuntimeWarning: invalid value encountered in double_scalars
  fitness_result[x] *= multiplier


ValueError: probabilities contain NaN